### ISSUE TITLE
ModuleNotFoundError: No module named 'regex._regex' on macOS 12.3

### ISSUE THREAD

**Issue by ytrms** [artyompetrov/AutoDefine_oxfordlearnersdictionaries#4]
**Describe the bug**
After installing the add-on, on Anki startup, the following traceback pops up, and the addon's button does not appear in the card editor:

```
When loading '⁨AutoDefine Oxford Learners Dictionaries - automatically define words⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/Users/lorenzo/Library/Application Support/Anki2/addons21/570730390/__init__.py", line 1, in <module>
    from . import autodefine
  File "/Users/lorenzo/Library/Application Support/Anki2/addons21/570730390/autodefine.py", line 47, in <module>
    nltk = path_import('nltk')
  File "/Users/lorenzo/Library/Application Support/Anki2/addons21/570730390/autodefine.py", line 43, in path_import
    spec.loader.exec_module(module)
  File "/Users/lorenzo/Library/Application Support/Anki2/addons21/570730390/modules/nltk/__init__.py", line 137, in <module>
    from nltk.text import *
  File "/Users/lorenzo/Library/Application Support/Anki2/addons21/570730390/modules/nltk/text.py", line 29, in <module>
    from nltk.tokenize import sent_tokenize
  File "/Users/lorenzo/Library/Application Support/Anki2/addons21/570730390/modules/nltk/tokenize/__init__.py", line 65, in <module>
    from nltk.tokenize.casual import TweetTokenizer, casual_tokenize
  File "/Users/lorenzo/Library/Application Support/Anki2/addons21/570730390/modules/nltk/tokenize/casual.py", line 49, in <module>
    import regex  # https://github.com/nltk/nltk/issues/2409
  File "/Users/lorenzo/Library/Application Support/Anki2/addons21/570730390/modules/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/Users/lorenzo/Library/Application Support/Anki2/addons21/570730390/modules/regex/regex.py", line 421, in <module>
    import regex._regex_core as _regex_core
  File "/Users/lorenzo/Library/Application Support/Anki2/addons21/570730390/modules/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'
```

**To Reproduce**
1. Install the add-on
2. Restart Anki. The error will pop up, and the addon will not be available to use.

**Expected behavior**
No errors on startup and add-on button should be visible in editor.

**Debug info:**
 - Anki 2.1.54
 - macOS 12.3
 - MacBook Pro M1

**Additional context (e.g., exception)**
I do have the `regex` package installed in my python3, if that is relevant to the issue.

**Comment by xtaltheo** [comment]
I'm new to this community, and I apologize if it's impolite to leave a comment in such a manner here... but yeah.. I have the same issue.

Anki 2.1.54
macOS 12.3
MacBook Pro M1

**Comment by artyompetrov** [comment]
@ytrms @xtaltheo I understand the problem, will try to fix it soon

**Comment by artyompetrov** [comment]
Add-on still may not be working on x86 versions of macOS, I have an idea how to fix it, but it will require more time.
